[package]
name = "webhdfs"
version = "0.1.0"
authors = ["Valery Vybornov <vvybornov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#reqwest = "0.9"

hyper = "0.12"
hyper-tls = "0.3"
#tokio-tls = "0.2"
#native-tls = "0.2"
futures = "0.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
#serde = "1.0"
#serde_derive = "1.0"
log = "0.4"
tokio = "0.1"
http = "0.1"
mime = "0.3"
#base64 = "0.9"
