[package]
name = "webhdfs"
version = "0.2.1"
authors = ["Valery Vybornov <vvybornov@gmail.com>"]
edition = "2018"

description = "Hadoop WebHDFS client library"
homepage = "https://github.com/vvvy/webhdfs-rs"
#documentation = "..."
repository = "https://github.com/vvvy/webhdfs-rs"
readme = "README.md"
keywords = ["hdfs", "webhdfs", "hadoop"]
categories = ["filesystem", "asynchronous"]
license = "Apache-2.0"

[dependencies]
hyper = "0.12"
hyper-tls = "0.3"
bytes = "0.4"
futures = "0.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tokio = "0.1"
http = "0.1"
mime = "0.3"
toml = "0.5"

[features]
default = ["zero-copy-on-write"]
zero-copy-on-write = []

[badges]
travis-ci = { repository = "https://travis-ci.org/vvvy/webhdfs-rs" }
maintenance = { status = "actively-developed" }